# Form implementation generated from reading ui file 'new_msg.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QListWidgetItem
from PyQt6.QtCore import pyqtSignal, QThread
from PyQt6.QtCore import *
import serial
import threading
import time
from itertools import repeat
from PyQt6.QtCore import Qt, QDate, QTime, QTimer
import string
import random

msg = []

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 541)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 161, 91))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(190, 60, 161, 91))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 30, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 230, 331, 31))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.lineEdit.setObjectName("lineEdit")
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(120, 255, 391, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 21, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.numberClicked(self.pushButton.text()))
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 40, 21, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 40, 21, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 40, 21, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 40, 21, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 40, 21, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 40, 21, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 40, 21, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 40, 21, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(280, 40, 21, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        #self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        #self.pushButton_11.setGeometry(QtCore.QRect(10, 70, 31, 23))
        #self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 40, 31, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(350, 40, 31, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 70, 31, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_15.setGeometry(QtCore.QRect(50, 70, 31, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_16.setGeometry(QtCore.QRect(90, 70, 31, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_17.setGeometry(QtCore.QRect(130, 70, 31, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_18.setGeometry(QtCore.QRect(170, 70, 41, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_19.setGeometry(QtCore.QRect(220, 70, 31, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_20.setGeometry(QtCore.QRect(260, 70, 46, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_21.setGeometry(QtCore.QRect(315, 70, 41, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(400, 60, 161, 91))
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 30, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_4.setGeometry(QtCore.QRect(570, 60, 161, 91))
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 30, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(950, 30, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.listWidget_5 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_5.setGeometry(QtCore.QRect(780, 60, 161, 91))
        self.listWidget_5.setObjectName("listWidget_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 30, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.listWidget_6 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_6.setGeometry(QtCore.QRect(950, 60, 161, 91))
        self.listWidget_6.setObjectName("listWidget_6")
        
        aircraft_list = ["Aircraft #1", "Aircraft #2", "Aircraft #3"]
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 230, 121, 31))
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(aircraft_list)
        
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(20, 160, 41, 24))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.clicked.connect(self.start)

        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(60, 160, 41, 24))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_23.clicked.connect(self.send)
        
        msg_type = ["Message"]
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(490, 230, 121, 31))
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItems(msg_type)   

        #self.timer = QTimer()
        #self.timer.timeout.connect(self.push_data)
        #self.timer.start(3000) 

        # self.timer_2 = QTimer()
        # self.timer_2.timeout.connect(self.update_data)
        # self.timer_2.start(2000) 
        
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(620, 230, 111, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Msg Box"))
        self.listWidget.setSortingEnabled(False)
        self.label.setText(_translate("MainWindow", "Aircraft #1 Rx"))
        self.label_2.setText(_translate("MainWindow", "Aircraft #1 Tx"))
        self.pushButton.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "3"))
        self.pushButton_5.setText(_translate("MainWindow", "4"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "6"))
        self.pushButton_8.setText(_translate("MainWindow", "7"))
        self.pushButton_9.setText(_translate("MainWindow", "8"))
        self.pushButton_10.setText(_translate("MainWindow", "9"))
        #self.pushButton_11.setText(_translate("MainWindow", "ENT"))
        self.pushButton_12.setText(_translate("MainWindow", ">>"))
        self.pushButton_13.setText(_translate("MainWindow", "<<"))
        self.pushButton_14.setText(_translate("MainWindow", "ESC"))
        self.pushButton_15.setText(_translate("MainWindow", "TGT"))
        self.pushButton_16.setText(_translate("MainWindow", "LL"))
        self.pushButton_17.setText(_translate("MainWindow", "RR"))
        self.pushButton_18.setText(_translate("MainWindow", "CNFM"))
        self.pushButton_19.setText(_translate("MainWindow", "ACK"))
        self.pushButton_20.setText(_translate("MainWindow", "ALOK"))
        self.pushButton_21.setText(_translate("MainWindow", "ABRT"))
        self.label_3.setText(_translate("MainWindow", "Aircraft #2 Rx"))
        self.label_4.setText(_translate("MainWindow", "Aircraft #2 Tx"))
        self.label_5.setText(_translate("MainWindow", "Delegate Message"))
        self.label_6.setText(_translate("MainWindow", "Aircraft #3 Tx"))
        self.label_7.setText(_translate("MainWindow", "Aircraft #3 Rx"))
        self.pushButton_22.setText(_translate("MainWindow", "Start"))
        self.pushButton_23.setText(_translate("MainWindow", "Send"))
        self.pushButton_24.setText(_translate("MainWindow", "ENT"))

   
    def numberClicked(self, text_value):
        """When a button with a digit is pressed, check if the text for QLineEdit widgets are empty. If empty,
        set the focus to the correct widget and enter text value."""
        if self.lineEdit.text() == "":
            self.lineEdit.setFocus()
            self.lineEdit.setText(text_value)
            self.lineEdit.repaint() # ensure that text is updated in the QLineEdit widgets
        #elif (self.ui.lineEdit_1.text() != "") and (self.ui.lineEdit_2.text() == ""):
        #    self.ui.lineEdit_2.setFocus()
        #    self.ui.lineEdit_2.setText(text_value)
        #    self.ui.lineEdit_2.repaint()
        #elif (self.ui.lineEdit_1.text() != "") and (self.ui.lineEdit_2.text() != "") and (self.ui.lineEdit_3.text() == ""):
        #    self.ui.lineEdit_3.setFocus()
        #    self.ui.lineEdit_3.setText(text_value)
        #    self.ui.lineEdit_3.repaint()
        #elif (self.ui.lineEdit_1.text() != "") and (self.ui.lineEdit_2.text() != "") and (self.ui.lineEdit_3.text() != "") and (self.ui.lineEdit_4.text() == ""):
        #    self.ui.lineEdit_4.setFocus()
        #    self.ui.lineEdit_4.setText(text_value)
        #    self.ui.lineEdit_4.repaint()
    

    #def get_data(self):
    #    ser = serial.Serial('COM12', 9600, timeout=0.9)
    #    data_in = ser.readline()
    #    self.msg.insert(0, str(data_in))
    
    #def job1():
    #    def gen():
    #        res = ''.join(random.choices(string.ascii_uppercase + string.digits, k = 1))
    #        return str(res)
    #    
    #    self.msg.insert(0, gen())
    
    
    #def push_data(self):
    #    #def gen():
    #        #res = ''.join(random.choices(string.ascii_uppercase + string.digits, k = 10))
    #        #return str(res)
    #    ser = serial.Serial('COM12', 9600, timeout=0.9)
    #    while 1:
    #        data_in = ser.readline()
    #        #print(data_in)
    #        self.msg.insert(0, str(data_in))
    #    ser.close()
        #for i in range(20):
            #time.sleep(0.1)
        #self.msg.insert(0, gen())
        #for i in self.msg:
        #    self.list_item = QListWidgetItem()
        #    self.list_item.setText(i)
        #    self.listWidget.addItem(self.list_item)
    
    #def print_cube(self):
    #    #for i in self.msg:
    #    #    self.list_item = QListWidgetItem()
    #    #    self.list_item.setText(i)
    #    #    self.listWidget.addItem(self.list_item)
    #    #ser = serial.Serial('COM12', 9600, timeout=0.9)
    #    #for _ in itertools.repeat(None, self.msg):
    #        #data_in = ser.readline()
    #        #self.msg.insert(0, str(data_in))
    #    for i in repeat(None, 20):
    #        self.get_data()

    #def print_square(self):
    #    #for i in self.msg:
    #    #    self.list_item = QListWidgetItem()
    #    #    self.list_item.setText(i)
    #    #    self.listWidget_2.addItem(self.list_item)
    #    for i in repeat(None, 10):
    #        self.push_data()
    def start(self):
        print('Starting Thread')
        self.worker = WorkerThread()
        self.worker.start()       

    def send(self):
        print('sending data')
        temp = 'TestThisShit\r\n'
        arr2 = bytes(temp, 'ascii')
        ser.write(arr2)
    
    def update_data(self):
        for item in msg:
            self.list_item = QListWidgetItem()
            self.list_item.setText(item)
            self.listWidget.addItem(self.list_item)
        #t1 = threading.Thread(self.print_cube())
        #t2 = threading.Thread(self.print_square())
        #t1.start()
        #t2.start()

    def init_serial(self):
        #COMNUM = 4          #Enter Your COM Port Number Here.
        global ser          #Must be declared in Each Function
        ser = serial.Serial()
        ser.baudrate = 9600
        ser.port = 'COM12'   #COM Port Name Start from 0
        
        #ser.port = '/dev/ttyUSB0' #If Using Linux

        #Specify the TimeOut in seconds, so that SerialPort
        #Doesn't hangs
        ser.timeout = 10
        ser.open()          #Opens SerialPort

        # print port open or closed
        if ser.isOpen():
            print ('Open: ' + ser.portstr)
    #Function Ends Here    


class WorkerThread(QThread):
    def run(self):
        # ser = serial.Serial('COM12', 9600, timeout=0.9)
        while 1:
            # print(ser)
            data_in = ser.readline()
            #print(data_in)
            # msg.insert(0, str(data_in))
            print('Printing')
            print(data_in.decode('ascii'))
            # QListWidgetItem(data_in.decode('UTF-8'), self.listWidget)
            #print(msg)    
        
        
        

if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.init_serial()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
    
