# Form implementation generated from reading ui file 'clean.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import vlc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        
        self.instance = vlc.Instance()
        self.mediaplayer = self.instance.media_player_new()
        media = vlc.Instance().media_new("rtsp://192.168.1.106:554/user=admin&password=admin@1234&channel=1&stream=0.sdp")
        self.mediaplayer.set_media(media)
        self.mediaplayer.set_hwnd(self.frame.winId())

        self.verticalLayout.addWidget(self.frame)
        
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 311, 311, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.playbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.playbutton.setObjectName("playbutton")
        self.playbutton.clicked.connect(self.PlayPause)

        self.horizontalLayout.addWidget(self.playbutton)
        
        self.volumeslider = QtWidgets.QSlider(self.layoutWidget)
        self.volumeslider.setMaximum(100)
        self.volumeslider.setValue(self.mediaplayer.audio_get_volume())
        self.volumeslider.valueChanged.connect(self.setVolume)
        self.volumeslider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeslider.setObjectName("volumeslider")
        
        self.horizontalLayout.addWidget(self.volumeslider)
        
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(341, 311, 311, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.playbutton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.playbutton_4.setObjectName("playbutton_4")
        self.playbutton_4.clicked.connect(self.PlayPause1)
        
        self.horizontalLayout_4.addWidget(self.playbutton_4)
        
        self.volumeslider_4 = QtWidgets.QSlider(self.layoutWidget_2)
        self.volumeslider_4.setMaximum(100)
        self.volumeslider_4.setValue(self.mediaplayer.audio_get_volume())
        self.volumeslider_4.valueChanged.connect(self.setVolume1)
        self.volumeslider_4.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeslider_4.setObjectName("volumeslider_4")
        
        self.horizontalLayout_4.addWidget(self.volumeslider_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(340, 10, 311, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")

        self.instance1 = vlc.Instance()
        self.mediaplayer1 = self.instance1.media_player_new()
        media1 = vlc.Instance().media_new("rtsp://192.168.1.106:554/user=admin&password=admin@1234&channel=4&stream=0.sdp")
        self.mediaplayer1.set_media(media1)
        self.mediaplayer1.set_hwnd(self.frame_2.winId())

        self.verticalLayout_4.addWidget(self.frame_2)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(671, 311, 311, 25))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.playbutton_5 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.playbutton_5.setObjectName("playbutton_5")
        self.playbutton_5.clicked.connect(self.PlayPause2)
        
        self.horizontalLayout_5.addWidget(self.playbutton_5)
        
        self.volumeslider_5 = QtWidgets.QSlider(self.layoutWidget_3)
        self.volumeslider_5.setMaximum(100)
        self.volumeslider_5.setValue(self.mediaplayer.audio_get_volume())
        self.volumeslider_5.valueChanged.connect(self.setVolume2)
        self.volumeslider_5.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeslider_5.setObjectName("volumeslider_5")
        
        self.horizontalLayout_5.addWidget(self.volumeslider_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(670, 10, 311, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        self.frame_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_3.setEnabled(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")

        self.instance2 = vlc.Instance()
        self.mediaplayer2 = self.instance2.media_player_new()
        media2 = vlc.Instance().media_new("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4")
        self.mediaplayer2.set_media(media2)
        self.mediaplayer2.set_hwnd(self.frame_3.winId())
        
        self.verticalLayout_5.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def PlayPause(self):
        if self.mediaplayer.is_playing():
            self.mediaplayer.pause()
            self.playbutton.setText("Play")
            self.isPaused = True
        else:
            if self.mediaplayer.play() == -1:
                self.player.play()
                return
            self.mediaplayer.play()
            self.playbutton.setText("Pause")
            self.isPaused = False

    def PlayPause1(self):
        if self.mediaplayer1.is_playing():
            self.mediaplayer1.pause()
            self.playbutton_4.setText("Play")
            self.isPaused = True
        else:
            if self.mediaplayer1.play() == -1:
                self.player.play()
                return
            self.mediaplayer1.play()
            self.playbutton_4.setText("Pause")
            self.isPaused = False

    def PlayPause2(self):
        if self.mediaplayer2.is_playing():
            self.mediaplayer2.pause()
            self.playbutton_5.setText("Play")
            self.isPaused = True
        else:
            if self.mediaplayer2.play() == -1:
                self.player.play()
                return
            self.mediaplayer2.play()
            self.playbutton_5.setText("Pause")
            self.isPaused = False

    def setVolume(self, Volume):
        self.mediaplayer.audio_set_volume(Volume)

    def setVolume1(self, Volume):
        self.mediaplayer1.audio_set_volume(Volume)

    def setVolume2(self, Volume):
        self.mediaplayer1.audio_set_volume(Volume)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playbutton.setText(_translate("MainWindow", "Play"))
        self.playbutton_4.setText(_translate("MainWindow", "Play"))
        self.playbutton_5.setText(_translate("MainWindow", "Play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
