# Form implementation generated from reading ui file 'new_vlc.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame
import vlc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 341)
        self.instance = vlc.Instance()
        self.mediaplayer = self.instance.media_player_new()
        self.mediaplayer1 = self.instance.media_player_new()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.playbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playbutton.setObjectName("playbutton")
        self.playbutton.clicked.connect(self.PlayPause)

        self.horizontalLayout.addWidget(self.playbutton)
        self.volumeslider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.volumeslider.setMaximum(100)
        self.volumeslider.setValue(self.mediaplayer.audio_get_volume())
        self.volumeslider.valueChanged.connect(self.setVolume)
        self.volumeslider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeslider.setObjectName("volumeslider")
        
        self.horizontalLayout.addWidget(self.volumeslider)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(300, 250, 271, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.playbutton_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.playbutton_1.setObjectName("playbutton_1")
        self.playbutton_1.clicked.connect(self.PlayPause1)

        self.horizontalLayout_2.addWidget(self.playbutton_1)
        self.volumeslider_2 = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.volumeslider_2.setMaximum(100)
        self.volumeslider_2.setValue(self.mediaplayer.audio_get_volume())
        self.volumeslider_2.valueChanged.connect(self.setVolume1)
        self.volumeslider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeslider_2.setObjectName("volumeslider_2")
        
        self.horizontalLayout_2.addWidget(self.volumeslider_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 10, 271, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.isPaused = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playbutton.setText(_translate("MainWindow", "Play"))
        self.playbutton_1.setText(_translate("MainWindow", "Play"))

    def PlayPause(self):
        if self.mediaplayer.is_playing():
            self.mediaplayer.pause()
            self.playbutton.setText("Play")
            self.isPaused = True
        else:
            if self.mediaplayer.play() == -1:
                self.OpenFile()
                return
            self.mediaplayer.play()
            self.playbutton.setText("Pause")
            self.isPaused = False

    def PlayPause1(self):
        if self.mediaplayer.is_playing():
            self.mediaplayer.pause()
            self.playbutton_1.setText("Play")
            self.isPaused = True
        else:
            if self.mediaplayer.play() == -1:
                self.OpenFile1()
                return
            self.mediaplayer.play()
            self.playbutton_1.setText("Pause")
            self.isPaused = False

    def OpenFile(self, filename=None):
        self.media = self.instance.media_new('rtsp://192.168.1.106:554/user=admin&password=admin@1234&channel=4&stream=0.sdp')
        self.mediaplayer.set_media(self.media)
        self.media.parse()
        if sys.platform == "win32": 
            self.mediaplayer.set_hwnd(self.frame.winId())
        self.PlayPause()

    def OpenFile1(self, filename=None):
        self.media = self.instance.media_new('rtsp://192.168.1.106:554/user=admin&password=admin@1234&channel=2&stream=0.sdp')
        self.mediaplayer.set_media(self.media)
        self.media.parse()
        self.mediaplayer.set_hwnd(self.frame_2.winId())
        self.PlayPause1()

    def setVolume(self, Volume):
        self.mediaplayer.audio_set_volume(Volume)

    def setVolume1(self, Volume):
        self.mediaplayer1.audio_set_volume(Volume)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
